app = "Bot System"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1m"
    restart_limit = 0

[processes]
  app = ""
  cron = "0 7 * * * /app/setup.sh"
  init = "/app/setup.sh"